
defaults:
  - identify_associations_bayes

batch_size: 10

num_refits: 10

target_dataset: random.continuous.proteomics 
target_value: plus_std
save_refits: True

model:
  num_hidden:
    - 100 
  num_latent: 50 
  beta: .0001
  dropout: .1 

training_loop:
  lr: 1e-4
  num_epochs: 200
